showing qbo errors in UI
fylein/fyle-qbo-api pull request #107
Opened 2021-06-29 06:43 UTC by NileshPant1999

2021-06-29 07:00 UTC, Sravanksk commented on apps/quickbooks_online/tasks.py
> +    error_msg = 'Failed to creaetm {0} in you quickbooks online account.'.format(export_type)
type `create`

2021-06-29 07:01 UTC, Sravanksk commented on apps/quickbooks_online/tasks.py
> +        handle_quickbooks_error(exception, expense_group, task_log, 'Expense')
handle exception for `journal_entries` also

2021-06-29 07:04 UTC, Sravanksk commented on apps/quickbooks_online/tasks.py
> +        handle_quickbooks_error(exception, expense_group, task_log, 'CHEQUE')
`CHECK`

2021-06-29 07:05 UTC, Sravanksk commented on apps/quickbooks_online/tasks.py
> +
rm extra space

2021-06-29 07:08 UTC, Sravanksk commented on apps/quickbooks_online/tasks.py
> +            'type': response['Fault']['type'] +' / ' + error['code'],
use .format()

2021-06-30 05:53 UTC, ashwin1111 commented on apps/quickbooks_online/tasks.py
> +        handle_quickbooks_error(exception, expense_group, task_log, 'Check')
`Check` is the spelling right?

2021-06-30 06:00 UTC, ashwin1111 requested changes

2021-06-30 06:09 UTC, ashwin1111 requested changes

2021-06-30 06:09 UTC, ashwin1111 commented on apps/tasks/models.py
> +    quickbooks_errors = JSONField(help_text='Quickbooks Errors', null=True)
how are we planning to migrate existing qbo errors from detail column to this?

2021-07-01 08:18 UTC, ashwin1111 commented on apps/tasks/urls.py
> +
rm extra lines

2021-07-05 06:15 UTC, NileshPant1999 commented on apps/quickbooks_online/tasks.py
> +    quickbooks_errors = response['Fault']['Error']
payment exception:  {"Fault":{"Error":[{"Message":"Object Not Found","Detail":"Object Not Found : Something you're trying to use has been made inactive. Check the fields with accounts, customers, items, vendors or employees.","code":"610","element":""}],"type":"ValidationFault"},"time":"2021-07-04T22:59:08.251-07:00"}

export exception: {"Fault":{"Error":[{"Message":"Account Period Closed","Detail":"The account period has closed. Txn Date=02/13/2019 is before book closing date=06/27/2021","code":"6200","element":""}],"type":"ValidationFault"},"time":"2021-06-27T22:31:00.785-07:00"}

2021-07-05 09:17 UTC, NileshPant1999 commented on apps/tasks/models.py
> +    quickbooks_errors = JSONField(help_text='Quickbooks Errors', null=True)
We can use SQL script to do that i will update that.

2021-07-05 09:18 UTC, NileshPant1999 commented on apps/quickbooks_online/tasks.py
> +        handle_quickbooks_error(exception, expense_group, task_log, 'CHEQUE')
> `CHECK`

@ashwin1111

2021-07-06 07:43 UTC, ashwin1111 requested changes

2021-07-06 07:43 UTC, ashwin1111 commented on apps/quickbooks_online/tasks.py
> +        handle_quickbooks_error(exception, expense_group, task_log, 'Check')
fix this

2021-07-06 07:55 UTC, ashwin1111 approved these changes

2021-07-06 09:14 UTC, Shwetabhk commented on sql/scripts/009-workspace-reset.sql
> +where status = 'FAILED' and detail -> 'Fault' is not NULL;
this script is not saving things in this format right?
```python
{
    'expense_group_id': expense_group.id,
    'type': '{0} / {1}'.format(response['Fault']['type'], error['code']),
    'short_description': error['Message'] if error['Message'] else '{0} error'.format(export_type),
    'long_description': error['Detail'] if error['Detail'] else error_msg
}
```

this will not be parsed on the UI? Am I missing something?

2021-07-06 14:17 UTC, ashwin1111 commented on sql/scripts/009-workspace-reset.sql
> +where status = 'FAILED' and detail -> 'Fault' is not NULL;
+1, script has to be fixed

2021-07-07 08:01 UTC, Sravanksk commented
@NileshPant1999 please check this [commit](https://github.com/fylein/fyle-xero-api/commit/92eb220d17e0897a13c04c128e11bdf1bc91a11e) and take care of these changes too

2021-07-15 08:57 UTC, Shwetabhk commented on sql/scripts/009-workspace-reset.sql
> +rollback;
lets remove this file completely, not needed

2021-07-19 07:33 UTC, merged