Tax Support for quickbooks api
fylein/fyle-qbo-api pull request #132
Opened 2021-08-30 06:17 UTC by NileshPant1999

2021-09-03 11:17 UTC, Shwetabhk commented on apps/workspaces/utils.py
> +    schedule_taxgroups_creation(import_taxcodes=general_settings.import_taxcodes, workspace_id=workspace_id)
tax_groups

2021-09-03 11:18 UTC, Shwetabhk commented on apps/workspaces/utils.py
> +            'import_taxcodes': general_settings_payload['import_taxcodes'],
`import_tax_codes`

2021-09-03 11:18 UTC, Shwetabhk commented on apps/workspaces/models.py
> +    import_taxcodes = models.BooleanField(default=False, help_text='Auto import tax codes to Fyle')
import_tax_codes

2021-09-03 11:19 UTC, Shwetabhk commented on apps/quickbooks_online/views.py
> +            'CREDIT_CARD_ACCOUNT', 'BANK_ACCOUNT', 'TAX'
let's use `TAX_CODE` instead of `TAX`

2021-09-03 11:20 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +            #"CurrencyRef": {
why is this commented?

2021-09-03 11:21 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +            #'CurrencyRef': {
why commented?

2021-09-03 11:21 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +            #'CurrencyRef': {
why comented?

2021-09-03 11:22 UTC, NileshPant1999 commented on apps/quickbooks_online/utils.py
> +            #'CurrencyRef': {
ohh sorry forget to uncomment them some time qbo gives you an currency error of using multiple currency it is a hack for fix that 😛 will uncomment this.

2021-09-03 11:24 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +                    'TaxAmount': line.tax_amount,
Tax amount is there in bills but not there anywhere else. Any reason?

2021-09-03 11:25 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +        credentials_object.save()
remove extra space after `save()`

2021-09-03 11:25 UTC, Shwetabhk commented on apps/quickbooks_online/urls.py
> +    path('taxcodes/', TaxcodeView.as_view()),
tax_codes

2021-09-03 11:26 UTC, Shwetabhk commented on apps/quickbooks_online/views.py
> +class TaxcodeView(generics.ListCreateAPIView):
TaxCodeView

2021-09-03 11:26 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +#            "CurrencyRef": {
why commented?

2021-09-03 11:26 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +    def sync_taxcodes(self):
sync_tax_codes

2021-09-03 11:27 UTC, Shwetabhk commented on apps/quickbooks_online/utils.py
> +        for taxcode in taxcodes:
tax_code in tax_codes

2021-09-03 11:30 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +    elif qbo_attribute_type == 'TAX':
TAX or TAX_CODES?

2021-09-03 11:30 UTC, Shwetabhk commented on apps/mappings/tasks.py
> +        qbo_connection.sync_taxcodes()
tax_codes

2021-09-03 11:32 UTC, Shwetabhk commented on apps/mappings/models.py
> +    default_tax_code_name = models.CharField(max_length=255, help_text='QBO default Tax Code name', null=True)
Why do we need a default field?

2021-09-03 11:33 UTC, Shwetabhk commented on apps/fyle/views.py
> +class GetTaxGroups(generics.ListCreateAPIView):
view name is incorrect
it should be TaxGroupsView

2021-09-03 11:34 UTC, Shwetabhk commented on apps/fyle/platform_connector.py
> +
remove space

2021-09-03 11:34 UTC, Shwetabhk commented on apps/fyle/urls.py
> +    ExpenseGroupSettingsView, RefreshFyleDimensionView, SyncFyleDimensionView, GetTaxGroups
view name needs to change

2021-09-03 11:38 UTC, NileshPant1999 commented on apps/mappings/models.py
> +    default_tax_code_name = models.CharField(max_length=255, help_text='QBO default Tax Code name', null=True)
if the tax is enabled in quickbooks and we don't provide default tax code export will not happen it will throw an error

2021-09-03 11:39 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +    elif qbo_attribute_type == 'TAX':
it should be 'TAX_CODE'

2021-09-03 11:40 UTC, NileshPant1999 commented on apps/quickbooks_online/utils.py
> +                    'TaxAmount': line.tax_amount,
we need to take call weather to provide it or not as it is of no use tax amount is automatically get calculated in qbo we need not to send tax_amount.

2021-09-15 14:46 UTC, ashwin1111 reviewed
@NileshPant1999 there are few comments common for netsuite api as well as here, please to fix them. Will review post that.

2021-09-15 14:46 UTC, ashwin1111 commented on apps/fyle/models.py
> +    tax_amount = models.FloatField(null=True, help_text="Tax Amount")
single quotes everywhere to maintain consistency

2021-09-15 14:46 UTC, ashwin1111 commented on run.sh
> +python3 manage.py migrate
add bash alias on your local, don't change it here

2021-09-15 14:46 UTC, ashwin1111 commented on requirements.txt
> +qbosdk==0.12.0
platform sdk?

2021-09-15 14:46 UTC, ashwin1111 commented on apps/workspaces/views.py
> -                             'Please choose the correct aaaaa Quickbooks online account')
haha, this is from day 0

2021-09-15 16:17 UTC, NileshPant1999 commented on apps/quickbooks_online/utils.py
> +               "value": 'USD'
change this

2021-09-16 14:04 UTC, ashwin1111 requested changes

2021-09-16 14:04 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +        attribute_type='TAX_CODE', workspace_id=workspace_id).order_by('value', 'id')[offset:limit]
why do we need offset limit and where do we get this from?

2021-09-16 14:04 UTC, ashwin1111 commented on apps/mappings/tasks.py
> +    Mapping.bulk_create_mappings(paginated_qbo_attributes, 'TAX_GROUP', 'TAX_CODE', workspace_id)
where is paginated_qbo_attributes?

2021-09-16 14:04 UTC, ashwin1111 commented on apps/quickbooks_online/views.py
> +            attribute_type__in=attribute_types, workspace_id=self.kwargs['workspace_id']).order_by('value')
new line

2021-09-16 14:24 UTC, NileshPant1999 commented on apps/mappings/tasks.py
> +        attribute_type='TAX_CODE', workspace_id=workspace_id).order_by('value', 'id')[offset:limit]
sorry forget push these changes fixed it along with others

2021-09-16 14:44 UTC, ashwin1111 approved these changes

2021-09-20 04:29 UTC, ashwin1111 requested changes

2021-09-20 04:29 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +            #"CurrencyRef": {
Why is this commented?

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/urls.py
> +    path('<int:workspace_id>/qbo_credentials/', QBOCredentialView.as_view()),
Change this, have discussed

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +class QBOCredentialView(generics.ListCreateAPIView):
change this

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +            workspace = Workspace.objects.get(pk=kwargs['workspace_id'])
this isn't  needed

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +            qbo_credentials = QBOCredential.objects.filter(workspace=workspace).first()
`workspace_id=kwargs['workspace_id']`

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +            print(workspace)
remove loggers

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +            print(company_info)
same

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                json.loads(exception.response),
We shouldn't return the response from this exception, instead return a generic message. Ideally we should be catching just WrongParams Exception. I don't see any reason why this could happen.

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                qbo_credentials.country = country
where do we get this country from?

2021-09-20 04:29 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                qbo_credentials.company_name = company_name
where do we get this company_name from?

2021-09-20 14:49 UTC, ashwin1111 requested changes

2021-09-20 14:49 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                except Exception as exception:
Don't add generalised exceptions

2021-09-20 14:49 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                        status=status.HTTP_400_BAD_REQUEST
we shouldn't return 400 here, we should silently ignore the error in this step

2021-09-20 14:49 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                try:
Why is this needed in the else part? This would be executed when there is a connect after disconnect.

2021-09-20 14:49 UTC, ashwin1111 commented on apps/quickbooks_online/views.py
> +
return 400, else it might would throw 500 / doesn't return anything

2021-09-21 07:16 UTC, NileshPant1999 commented on apps/workspaces/views.py
> +                try:
removing this

2021-09-21 08:08 UTC, ashwin1111 approved these changes

2021-09-21 08:08 UTC, ashwin1111 commented on apps/quickbooks_online/views.py
> +                    'message': 'Quickbooks Online connection expired'
change the message

2021-09-21 08:08 UTC, ashwin1111 commented on apps/workspaces/views.py
> +                    logger.error('Quickbooks Online connection expired')
log the exception message and not generic one

2021-09-29 07:41 UTC, NileshPant1999 commented on apps/quickbooks_online/utils.py
> +        for line_item in journal_entry_lineitems:
add this loop in the above if condition

2021-09-29 09:00 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +            "GlobalTaxCalculation": "TaxInclusive",
take care of this

2021-09-29 11:45 UTC, ashwin1111 commented on apps/quickbooks_online/tasks.py
> +        if not (general_mapping.default_tax_code_id or general_mapping.default_tax_code_name):
why not add in a single statement?

2021-09-29 11:45 UTC, ashwin1111 commented on apps/quickbooks_online/tasks.py
> +        if not (general_mapping.default_tax_code_id or general_mapping.default_tax_code_name):
condition*

2021-09-29 12:23 UTC, NileshPant1999 commented on apps/quickbooks_online/tasks.py
> +        if not (general_mapping.default_tax_code_id or general_mapping.default_tax_code_name):
okay adding in same line

2021-09-29 13:32 UTC, merged