post expenses even when the accounting period is closed
fylein/fyle-qbo-api pull request #133
Opened 2021-09-02 18:43 UTC by NileshPant1999

2021-09-07 04:23 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +            error_response = json.loads(bad_request.response)['Fault']['Error'][0]
@NileshPant1999 bring this line inside if. Also, few questions
1. Do we get `['Fault']['Error']` in the error response for all kind of errors?
2. If yes, will it be a list every time?
3. if yes, will it have the 1st element every time for any kind of errors?

2021-09-07 04:25 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +            error_response = json.loads(bad_request.response)['Fault']['Error'][0]
Also can we do it this way,
```
if general_settings.forced_export:
    error_response = json.loads(bad_request.response)['Fault']['Error'][0]
    if error_response['Message'] == 'Account Period Closed' and error_response['code'] == '6200':
        # post_to_qbo()
else:
    raise

2021-09-07 04:26 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +                bills_payload['TxnDate'] = txn_date.strftime("%Y-%m-%d")
Do you think we need to store the updated date in db? either in exports* tables (not user visible) or expense groups(user visible)?
@Shwetabhk thoughts?

2021-09-07 04:27 UTC, ashwin1111 reviewed
Added few questions and suggestions, those will apply for all kind of exports.

2021-09-09 10:03 UTC, Sravanksk approved these changes

2021-09-09 10:47 UTC, NileshPant1999 commented on apps/quickbooks_online/utils.py
> +            error_response = json.loads(bad_request.response)['Fault']['Error'][0]
yes ['Fault']['Error'] is present in every response.
yes it is list every time and it is the first element every time.

2021-09-09 11:06 UTC, ashwin1111 approved these changes

2021-09-15 16:08 UTC, ashwin1111 requested changes

2021-09-15 16:08 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +                    bill = Bill.objects.get(expense_group=expense_group)
we already have the bill instance, this is not needed

2021-09-15 16:08 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +                    bill = Bill.objects.get(expense_group=expense_group)
same everywhere

2021-09-16 14:20 UTC, ashwin1111 approved these changes

2021-09-17 07:43 UTC, merged