Customized memo
fylein/fyle-qbo-api pull request #164
Opened 2021-12-14 09:47 UTC by Sravanksk

2021-12-20 07:25 UTC, Shwetabhk requested changes

2021-12-20 07:25 UTC, Shwetabhk commented on apps/quickbooks_online/models.py
> +    merchant = lineitem.vendor if lineitem.vendor else ''
A lot of places we're doing this if condition and setting to empty sting
lets make a function out of this

2021-12-20 07:25 UTC, Shwetabhk commented on apps/quickbooks_online/models.py
> +    memo = memo[:-3] if memo[-1] == ' ' else memo
This seems hacky, your for loop should take care of this

2021-12-20 07:25 UTC, Shwetabhk commented on apps/workspaces/models.py
> +    customized_memo = ArrayField(
rename to `memo_structure`

2021-12-20 07:25 UTC, Shwetabhk commented on apps/workspaces/models.py
> +    customized_memo = ArrayField(
Make sure and check that the correct order gets saved everytime

2021-12-20 07:25 UTC, Shwetabhk commented on apps/workspaces/utils.py
> +            'customized_memo': general_settings_payload['customized_memo'] if
This is not required, db model will automatically call the default function

2021-12-20 07:25 UTC, Shwetabhk commented on apps/workspaces/views.py
> +                status=status.HTTP_201_CREATED
use `200` instead of `201`

2021-12-20 07:25 UTC, Shwetabhk commented on apps/quickbooks_online/models.py
> +    workspace_general_settings = WorkspaceGeneralSettings.objects.get(workspace_id=workspace_id)
pass general settings from the task.py function to the model function to this function

2021-12-20 07:25 UTC, Shwetabhk commented on apps/quickbooks_online/models.py
> +    for field in customized_memo:
customized memo to be changed to memo_structure everywhere

2021-12-23 13:13 UTC, ashwin1111 approved these changes

2021-12-23 13:13 UTC, ashwin1111 commented on apps/workspaces/utils.py
> +from .models import get_default_memo_fields
Why is this required?

2021-12-23 13:27 UTC, merged