Phase-1: Migrate QBO to platform ( Expenses API )
fylein/fyle-qbo-api pull request #171
Opened 2022-01-10 04:17 UTC by Sravanksk

2022-01-10 06:10 UTC, Shwetabhk commented on apps/fyle/helpers.py
> +def compare_tpa_and_platform_expenses(tpa_expenses: List[dict], platform_expenses: List[dict], workspace_id: int) -> None:
Add a to do to remove this later

2022-01-10 06:12 UTC, Shwetabhk commented on fyle_qbo_api/settings.py
> +        'fyle_integrations_platform_connector': {
Add a to do to remove this later

2022-01-10 06:13 UTC, Shwetabhk commented on apps/fyle/tasks.py
> +            compare_tpa_and_platform_expenses(tpa_expenses, expenses, workspace_id)
Add a to do to clean this function up later

2022-01-10 06:14 UTC, Shwetabhk approved these changes

2022-01-10 10:28 UTC, NileshPant1999 commented on apps/fyle/models.py
> -                    'tax_group_id': expense['tax_group_id'],
@Sravanksk why you are removing these ??

2022-01-10 10:29 UTC, NileshPant1999 commented on apps/fyle/models.py
> -                    'billable': expense['billable'],
this too

2022-01-11 06:14 UTC, NileshPant1999 commented on apps/mappings/tasks.py
>              workspace_id=workspace_id
@Sravanksk the parameters are wrong !!

2022-01-19 07:35 UTC, ashwin1111 requested changes

2022-01-19 07:35 UTC, ashwin1111 commented on apps/fyle/models.py
> +                    'amount': round(expense['amount'], 2),
Why are we doing this additionally now?

2022-01-19 07:35 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +            updated_at_fyle_tpa = []
not needed

2022-01-19 07:35 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +                updated_at_fyle_tpa.append(
not needed

2022-01-19 07:35 UTC, ashwin1111 commented on requirements.txt
> +fyle==0.21.0
why is this needed? connector library takes care of this

2022-01-19 07:39 UTC, Sravanksk commented on apps/fyle/models.py
> +                    'amount': round(expense['amount'], 2),
not needed, removing

2022-01-19 07:49 UTC, Sravanksk commented on requirements.txt
> +fyle==0.21.0
yes, not needed, removing

2022-01-19 07:52 UTC, ashwin1111 approved these changes

2022-01-19 07:54 UTC, merged