Qbo cards mapping
fylein/fyle-qbo-api pull request #176
Opened 2022-01-24 12:13 UTC by Sravanksk

2022-01-25 14:38 UTC, ashwin1111 requested changes

2022-01-25 14:38 UTC, ashwin1111 commented on apps/mappings/constants.py
> +    'corporate_card'
didn't get it, is there any system field for this? I am able to create a select type custom field via UI for corporate card

2022-01-25 14:38 UTC, ashwin1111 commented on apps/quickbooks_online/models.py
> +                if workspace_general_settings.map_fyle_cards_qbo_account:
can you move this block of code to a separate function pliss, duplicate code

2022-01-25 14:38 UTC, ashwin1111 commented on apps/workspaces/utils.py
> +    if not general_settings.map_fyle_cards_qbo_account:
Didn't get this, why are we doing something like delete via code?

2022-01-25 14:38 UTC, ashwin1111 commented on apps/workspaces/utils.py
> +            mapping_setting.delete()
todo item for me - understand how are we planning to migrate existing customers

2022-01-27 07:47 UTC, Sravanksk commented on apps/workspaces/utils.py
> +    if not general_settings.map_fyle_cards_qbo_account:
if configuration updates happen, we should delete mapping settings right, otherwise we end up showing Cards mapping tab

2022-01-27 07:47 UTC, Sravanksk commented on apps/workspaces/utils.py
> +            mapping_setting.delete()
will be adding a sql script for migrating all existing customers

2022-01-31 13:47 UTC, ashwin1111 commented on apps/mappings/constants.py
> +    'corporate_card'
@Sravanksk did you find out the reason behind this?

2022-01-31 13:47 UTC, ashwin1111 commented on apps/quickbooks_online/models.py
> +def get_ccc_account_id(workspace_general_settings, general_mappings, expense, description):
param and return type pleaseee

2022-01-31 13:47 UTC, ashwin1111 approved these changes

2022-01-31 16:33 UTC, Sravanksk commented on apps/mappings/constants.py
> +    'corporate_card'
fixed in this commit 
https://github.com/fylein/fyle-qbo-api/pull/176/commits/13ec536cd50781542c28d271fbbbe95c77998e1a

2022-01-31 16:33 UTC, merged