email notification Back-end commit
fylein/fyle-qbo-api pull request #289
Opened 2022-07-14 10:09 UTC by DhaaraniCIT

2022-07-15 19:59 UTC, Sravanksk commented on apps/workspaces/models.py
> +    workspace = models.OneToOneField(Workspace, on_delete=models.PROTECT, help_text='Reference to Workspace model')
why is this changed? Any particular reason?

2022-07-15 20:04 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +from fyle_accounting_mappings.models import MappingSetting, ExpenseAttribute
move this import above line 12 and `MappingSetting` is imported but not being used anywhere in the code

2022-07-15 20:09 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +        ~Q(type__in=['CREATING_REIMBURSEMENT', 'FETCHING_EXPENSES', 'CREATING_AP_PAYMENT']),
This has to be fixed as per QBO task_logs, please check the code and figure this out

2022-07-15 20:11 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +                    subject="Export To QuickBooks Failed",
Quickbooks -> `QuickBooks Online`

2022-07-15 20:12 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +                    from_email=settings.EMAIL,
add this env variable from_email (`EMAIL`) to settings.py file

2022-07-15 20:13 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +              background="https://raw.githubusercontent.com/fylein/fyle-netsuite-api/b1ebe6c1db08c4e85cc34244f8bf5a1b3f1219ea/apps/workspaces/templates/images/background.png"
these images are pointing to netsuite-api, please fix

2022-07-15 20:13 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                      src="https://raw.githubusercontent.com/fylein/fyle-netsuite-api/e05abf142208368b88a530f3d8bb25456fef4d26/apps/workspaces/templates/images/icon.png">
same

2022-07-15 20:14 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                    <img src="https://sage-intacct.fyleapps.tech/assets/images/pngs/fyle-logo.png" alt="Fyle" title="Fyle"
same, this is pointing to intacct staging assets

2022-07-15 20:14 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                      src="https://sage-intacct.fyleapps.tech/assets/images/pngs/sage-intacct-logo.png"
same

2022-07-15 20:14 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                        <td>SAGE INTACCT ENTITY</td>
remove sage-intacct references everywhere

2022-07-15 20:14 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                        <td>{{ intacct_company }}</td>
same

2022-07-15 20:15 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                          to Sage Intacct Entity
same

2022-07-15 20:15 UTC, Sravanksk commented on apps/workspaces/templates/mail_template.html
> +                          Typically, expenses fail to export because of missing mapping or Sage Intacct authorization issues
same

2022-07-18 05:17 UTC, DhaaraniCIT commented on apps/workspaces/models.py
> +    workspace = models.OneToOneField(Workspace, on_delete=models.PROTECT, help_text='Reference to Workspace model')
related name has reference in advanced setting api

2022-07-18 05:55 UTC, DhaaraniCIT commented on apps/workspaces/tasks.py
> +                    from_email=settings.EMAIL,
It is already in setting.py

2022-07-19 07:44 UTC, NileshPant1999 commented on apps/workspaces/tasks.py
> +import time
no reference

2022-07-19 07:45 UTC, NileshPant1999 commented on apps/workspaces/tasks.py
> +                'next_run': datetime.now() + timedelta(minutes=1)
remember to change this later after testing

2022-07-19 07:49 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SENDGRID_ECHO_TO_STDOUT=True
I need to test one thing here, set it to false in the local system and see if the email body still shows up in the terminal

2022-07-19 07:49 UTC, NileshPant1999 commented on requirements.txt
> +django-sendgrid-v5==1.2.0
Can we place it alphabetically ??

2022-07-19 07:51 UTC, NileshPant1999 commented on apps/workspaces/views.py
> -        schedule_enabled = request.data.get('schedule_enabled')
why are we changing this, will be better if we get them in the previous format, the camel case is not a good practice in python

2022-07-19 07:52 UTC, NileshPant1999 commented on apps/workspaces/templates/mail_template.html
> +</html>
new line

2022-07-20 10:47 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SENDGRID_ECHO_TO_STDOUT=True
@DhaaraniCIT did you test this ??

2022-07-20 11:10 UTC, DhaaraniCIT commented on fyle_qbo_api/settings.py
> +SENDGRID_ECHO_TO_STDOUT=True
yes, if it is false it does'n show the email html code in terminal

2022-07-25 11:54 UTC, Sravanksk commented on apps/workspaces/models.py
> +    workspace = models.OneToOneField(Workspace, on_delete=models.PROTECT, help_text='Reference to Workspace model',
remove extra space, this line change is not needed

2022-07-25 11:56 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +from fyle_accounting_mappings.models import ExpenseAttribute
place this after line 10 ( module imports should be above app imports )

2022-07-25 11:58 UTC, DhaaraniCIT commented on apps/workspaces/models.py
> +    workspace = models.OneToOneField(Workspace, on_delete=models.PROTECT, help_text='Reference to Workspace model',
this line is required

2022-07-25 12:02 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +    expence_html = ''
fix typo expence_html -> `expense_html`

2022-07-25 12:02 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +        ~Q(type__in=['CREATING_REIMBURSEMENT', 'FETCHING_EXPENSES', 'CREATING_AP_PAYMENT']),
This is not fixed yet, please check different types of tasks in qbo_staging db and add filters accordingly

2022-07-25 12:04 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +        if error.type == 'EMPLOYEE_MAPPING' or error.type == 'CATEGORY_MAPPING' and count < 5:
why are we checking for count < 5? Can you explain or add a comment to the code?

2022-07-25 12:04 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +            error_type = org_type[0][0]+org_type[0][1:].lower()+' '+org_type[1][0]+org_type[1][1:].lower()
fix indentation

2022-07-25 12:06 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +            expence_html = expence_html + html
expence_html = expence_html + html -> `expense_html = '{0} {1}'.format(expense_html, html)`

2022-07-25 12:07 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +            error_type = org_type[0][0]+org_type[0][1:].lower()+' '+org_type[1][0]+org_type[1][1:].lower()+' '+org_type[2][0]+org_type[2][1:].lower()
fix indentation and also try to use string formatting everywhere ( `.format()` )

2022-07-25 12:07 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +            expence_html = expence_html + html
same

2022-07-25 12:07 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +            error_type = org_type[0][0]+org_type[0][1:].lower()+' '+org_type[1][0]+org_type[1][1:].lower()
same

2022-07-25 12:07 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +            expence_html = expence_html + html
same

2022-07-25 12:08 UTC, Sravanksk commented on apps/workspaces/tasks.py
> +                    'task_logs': mark_safe(expence_html),
fix typo expence_html

2022-07-25 12:08 UTC, DhaaraniCIT commented on apps/workspaces/tasks.py
> +        if error.type == 'EMPLOYEE_MAPPING' or error.type == 'CATEGORY_MAPPING' and count < 5:
no of row in email is limited to 5, that why i have stated as 5

2022-07-25 12:10 UTC, Sravanksk commented on apps/workspaces/views.py
>              )
add two line breaks after every class

2022-07-25 12:12 UTC, DhaaraniCIT commented on apps/workspaces/tasks.py
> +            error_type = org_type[0][0]+org_type[0][1:].lower()+' '+org_type[1][0]+org_type[1][1:].lower()
fix indentation means how you are meaning

2022-07-28 11:52 UTC, Sravanksk approved these changes

2022-07-28 13:36 UTC, ashwin1111 requested changes

2022-07-28 13:36 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +    ws_schedule, _ = WorkspaceSchedule.objects.get_or_create(
why is this `get_or_create()` and not `.get()`? This function will be called by the worker only when the setting is enabled no?

2022-07-28 13:36 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +    admin_data = WorkspaceSchedule.objects.get(workspace_id=workspace_id)
We already have access to this in `ws_schedule`

2022-07-28 13:36 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +    errors = Error.objects.filter(workspace_id=workspace_id)
We should add `is_resolved=false` as well, else we might end up sending emails for resolved ones as well

2022-07-28 13:36 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +    if ws_schedule.enabled:
Why not add this filter directly in the above query? If it's false, all the above operations doesn't add any value.

2022-07-28 13:36 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +                    'workspace_id': workspace_id,
where is this used?

2022-07-28 13:36 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +                    'app_url': "{0}/workspaces/main/dashboard".format(settings.FYLE_APP_URL),
this needs to be added to https://github.com/fylein/fyle-deploy

2022-07-28 13:36 UTC, ashwin1111 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
where is this used?

2022-07-28 13:36 UTC, ashwin1111 commented on fyle_qbo_api/settings.py
> +SI_SENDER_PASSWORD = os.environ.get('SI_SENDER_PASSWORD')
where is this used?

2022-07-28 14:19 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
@ashwin1111 this is required by sendgrid

2022-07-28 14:20 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SI_SENDER_PASSWORD = os.environ.get('SI_SENDER_PASSWORD')
same required by sendgrid

2022-07-28 14:22 UTC, NileshPant1999 commented on apps/workspaces/templates/mail_template.html
> +</html>
@DhaaraniCIT why did you marked it as resolved ??

2022-07-28 14:28 UTC, ashwin1111 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
I see just send grid key and email used.

2022-07-28 14:28 UTC, NileshPant1999 commented on apps/workspaces/tasks.py
> +    errors = Error.objects.filter(workspace_id=workspace_id)
@ashwin1111 we are only sending email when len(task_logs) > error_count, so even if the customer fixed some of the mappings we will not send the email again as the len(task_logs) then will be less then error count. can explain tomorrow if not clear.

2022-07-28 14:34 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +    errors = Error.objects.filter(workspace_id=workspace_id)
this returns all historical data which is not at all needed. assume a large org have few hundred errors. we are only concerned about non resolved errors

2022-07-29 06:27 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
this is in their document, so i added that, @DhaaraniCIT can you please try to remove it and see if it fails, may be this is used internally

2022-07-29 06:29 UTC, ashwin1111 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
this is Intacct sender ID and pwd saaar :D

2022-07-29 06:29 UTC, ashwin1111 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
where did you find it from the docs :P

2022-07-29 07:12 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
ohh i thought it is sendgrid ID 🤣

2022-07-29 07:14 UTC, NileshPant1999 commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
My bad @DhaaraniCIT please remove this

2022-07-29 07:23 UTC, DhaaraniCIT commented on fyle_qbo_api/settings.py
> +SI_SENDER_ID = os.environ.get('SI_SENDER_ID')
@NileshPant1999 and @ashwin1111 are you talking about this "SENDGRID_ECHO_TO_STDOUT" or "sendgrid ID"

2022-08-02 05:58 UTC, ashwin1111 requested changes

2022-08-02 05:58 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +    if ws_schedule.enabled:
Why is this still needed?

2022-08-02 05:58 UTC, ashwin1111 commented on apps/workspaces/tasks.py
> +        error_type = '{0} {1}'.format(org_type[0][0]+org_type[0][1:].lower(), org_type[1][0]+org_type[1][1:].lower())
instead of doing this, can do this, looks more neat and not hacky `error.type.lower().title().replace('_', ' ')`

2022-08-02 06:26 UTC, DhaaraniCIT commented on apps/workspaces/tasks.py
> +    if ws_schedule.enabled:
is this commend for **"if ws_schedule.enabled:"** this line

2022-08-02 07:11 UTC, ashwin1111 approved these changes

2022-08-05 05:15 UTC, merged