modified tests to include all if cases for auto create vendor
fylein/fyle-qbo-api pull request #333
Opened 2022-09-27 13:08 UTC by harshithaputtaswamy

2022-09-28 05:24 UTC, ashwin1111 commented on tests/test_quickbooks_online/test_tasks.py
> +    assert contact != None
can we assert with the actual expected result?

2022-09-29 14:16 UTC, Shwetabhk approved these changes

2022-09-29 14:17 UTC, Shwetabhk requested changes
remove -vv file

2022-10-03 09:48 UTC, ashwin1111 approved these changes

2022-10-03 12:12 UTC, Shwetabhk approved these changes

2022-10-03 12:29 UTC, merged