Clean up tasks on exports polling
fylein/fyle-qbo-api pull request #35
Opened 2021-01-25 16:38 UTC by KirtiGautam

- Updated expense group creation method to either update previously created objects in import or create new only if it doesn't exist.
- Wrote a script to delete redundant entries in the database.

2021-01-25 16:53 UTC, ashwin1111 requested changes

2021-01-25 16:53 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +    task_log, created = TaskLog.objects.get_or_create(
We need update or create here.

2021-01-25 17:23 UTC, ashwin1111 commented on apps/fyle/tasks.py
> +    task_log, created = TaskLog.objects.get_or_create(
ignore, didn't notice the  .save() part. this is fine.

2021-01-25 17:24 UTC, ashwin1111 approved these changes

2021-01-25 17:25 UTC, KirtiGautam commented on apps/fyle/tasks.py
> +    task_log, created = TaskLog.objects.get_or_create(
There's a save method called below. It will update the object as soon as it hits save. We don't need to run the update method twice.

2021-01-25 17:28 UTC, KirtiGautam commented on apps/fyle/tasks.py
> +    task_log, created = TaskLog.objects.get_or_create(
Okay 😊

2021-01-28 05:59 UTC, Shwetabhk commented on scripts/004-task-cleanup.sql
> +Delete from task_logs where type='FETCHING_EXPENSES' and status='COMPLETE';
Change `Delete` to `delete`

2021-01-28 06:00 UTC, Shwetabhk commented on scripts/004-task-cleanup.sql
> +Delete from task_logs where type='FETCHING_EXPENSES' and status='COMPLETE';
Delete would also work, but we use only lowercase for SQL keywords

2021-01-28 06:00 UTC, Shwetabhk approved these changes

2021-01-28 06:01 UTC, KirtiGautam commented on scripts/004-task-cleanup.sql
> +Delete from task_logs where type='FETCHING_EXPENSES' and status='COMPLETE';
Okay, making the required changes.

2021-01-28 06:35 UTC, merged