post-date-integration-support for qbo changes
fylein/fyle-qbo-api pull request #448
Opened 2023-06-21 13:59 UTC by DhaaraniCIT

2023-06-23 09:44 UTC, ashwin1111 commented on tests/test_quickbooks_online/test_utils.py
> -    cheque_object['Line'][1]['DetailType'] == 'AccountBasedExpenseLineDetail'
why is this removed?

2023-06-23 09:44 UTC, ashwin1111 commented on tests/test_quickbooks_online/fixtures.py
> +                "AccountBasedExpenseLineDetail":{
why are these changed?

2023-06-23 09:47 UTC, DhaaraniCIT commented on tests/test_quickbooks_online/test_utils.py
> -    cheque_object['Line'][1]['DetailType'] == 'AccountBasedExpenseLineDetail'
codecov gave command that 'there is no effect', so changed

2023-06-23 09:47 UTC, DhaaraniCIT commented on tests/test_quickbooks_online/fixtures.py
> +                "AccountBasedExpenseLineDetail":{
the unit test was failing, because the positions were differing when compared to the fixture the and resulted data

2023-06-23 09:48 UTC, ashwin1111 commented on tests/test_quickbooks_online/fixtures.py
> +                "AccountBasedExpenseLineDetail":{
ideally your changes doesn't touch these areas no? please discuss the failure with @labhvam5

2023-06-28 05:04 UTC, Shwetabhk requested changes

2023-06-28 05:04 UTC, Shwetabhk commented on tests/test_quickbooks_online/fixtures.py
> +                "AccountBasedExpenseLineDetail":{
I don't think the order matters, the failure could've been for some other reason, please check it with @labhvam5

2023-06-28 05:04 UTC, Shwetabhk commented on tests/test_quickbooks_online/fixtures.py
> +                "AccountBasedExpenseLineDetail":{
Ideally there should be no change in this file

2023-06-28 05:04 UTC, Shwetabhk commented on tests/test_quickbooks_online/test_utils.py
> -    cheque_object['Line'][1]['DetailType'] == 'AccountBasedExpenseLineDetail'
I think these are supposed to be asserts

2023-06-28 05:04 UTC, Shwetabhk commented on tests/test_quickbooks_online/test_utils.py
> -    cheque_object['Line'][1]['DetailType'] == 'AccountBasedExpenseLineDetail'
```python
    assert cheque_object['Line'][0]['DetailType'] == 'ItemBasedExpenseLineDetail'
    assert cheque_object['Line'][1]['DetailType'] == 'AccountBasedExpenseLineDetail'
```

2023-06-28 05:06 UTC, Shwetabhk commented on tests/test_fyle/test_models.py
> +def test_support_post_date_integrations(mocker, db, api_client, test_connection):
test name is not right, there is no where in this test where we're asserting whether the posted_at got save correctly in the db or not
Please add an assert for thay

2023-06-28 05:07 UTC, Shwetabhk commented on tests/test_fyle/test_models.py
> +    workspace_id = 3
this test is unnecessary and is already tested in views.py
We shouldn't add tests for views in test_models.py file

2023-06-28 05:07 UTC, Shwetabhk commented on tests/test_fyle/test_models.py
> +    assert task_log.status == 'COMPLETE'
Add more assertions to ensure that posted_at is saved correctly and is same as what's there in the fixtures

2023-06-28 05:09 UTC, Shwetabhk commented on tests/test_fyle/test_models.py
> +    workspace_id = 3
if you want to add a unit test for the whole flow add the test in test_quickbooks_online/test_models.py

Triggering the view cannot make sure that the correct posted_at is added because tests don't have access to DjangoQ.

2023-06-28 06:06 UTC, DhaaraniCIT commented on tests/test_quickbooks_online/fixtures.py
> +                "AccountBasedExpenseLineDetail":{
Got green for the changes from @labhvam5

2023-06-30 05:03 UTC, Shwetabhk commented on tests/test_quickbooks_online/test_utils.py
> +
remove extra spaces

2023-06-30 05:04 UTC, Shwetabhk approved these changes
@DhaaraniCIT approved with 1 minor comment, please fix it off before merging

2023-07-06 05:14 UTC, merged