Configure name for Journal entry
fylein/fyle-qbo-api pull request #470
Opened 2023-08-03 11:27 UTC by DhaaraniCIT

2023-08-08 12:57 UTC, labhvam5 requested changes

2023-08-08 12:57 UTC, labhvam5 commented on apps/quickbooks_online/utils.py
> +def create_entity_id(expense_group: ExpenseGroup, general_settings: WorkspaceGeneralSettings):
rename this function as `create_entity_id_map` since it is returning multiple values .

2023-08-08 12:57 UTC, labhvam5 commented on apps/quickbooks_online/helper.py
> +def create_vendor_destionation_attribute(name: str, workspace_id: int, general_settings: WorkspaceGeneralSettings):
Where is this function being used ?

2023-08-08 12:57 UTC, labhvam5 commented on apps/quickbooks_online/models.py
> +    def create_journal_entry_lineitems(expense_group: ExpenseGroup, workspace_general_settings: WorkspaceGeneralSettings, entity_ids):
change the entity_ids to entity_map . Pls refer the next comment down below for an explanation.

2023-08-08 12:57 UTC, labhvam5 commented on apps/quickbooks_online/utils.py
> +        current_entity = {
change the response structure to a map.

2023-08-10 05:21 UTC, labhvam5 requested changes

2023-08-10 05:21 UTC, labhvam5 commented on apps/quickbooks_online/utils.py
> +        return entity_ids
We should return `entity_map` not the `entity_ids`

2023-08-10 05:21 UTC, labhvam5 commented on apps/quickbooks_online/models.py
> +            entity_id = next((entity[lineitem.id] for entity in entity_map if lineitem.id in entity), None)
In here we can make use of the `entity_map` as 

`entity_id = entity_map[lineitem_id] `

2023-08-10 09:40 UTC, labhvam5 approved these changes

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/models.py
> +    def create_journal_entry_lineitems(expense_group: ExpenseGroup, workspace_general_settings: WorkspaceGeneralSettings, entity_map):
entity_map: Dict

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/tasks.py
> +        entity_map = qbo_connection.create_entity_id_map(expense_group, general_settings)
let's name it `get_or_create_entity`

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +    isEmployee: bool):
instead of isEmployee, get fund_source from Expense Group.

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +        if isEmployee:
`if fund_source == 'PERSONAL':`

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +                # check workspace_general_settings.Name is Merchant in Journal Entry (CCC)
comments are not needed for simple conditions, line 1090 and 1091 looks very similar

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +                merchant = DestinationAttribute.objects.filter(value__iexact=lineitem.vendor,
call it vendor instead of merchant

2023-08-10 09:59 UTC, ashwin1111 commented on apps/quickbooks_online/utils.py
> +        value = value if value else 'Credit Card Misc'
this is not needed, can just add `and value:` along with the existing conditions in line 1073

2023-08-10 09:59 UTC, ashwin1111 commented on apps/workspaces/models.py
> +        help_text='Name in jounral entry for ccc expense only',
Name in journal* entry typo

2023-08-10 09:59 UTC, ashwin1111 commented on apps/workspaces/migrations/0042_workspacegeneralsettings_name_in_journal_entry.py
> +                help_text='Name in jounral entry for ccc expense only',
Name in journal* entry typo

2023-08-10 09:59 UTC, ashwin1111 commented on apps/workspaces/models.py
> +        default=get_default_name_JE,choices=NAME_IN_JOURNAL_ENTRY)
default should be a string, 'EMPLOYEE'

2023-08-10 10:09 UTC, DhaaraniCIT commented on apps/quickbooks_online/utils.py
> +    isEmployee: bool):
it will be used for employee name setting also

2023-08-10 10:11 UTC, DhaaraniCIT commented on apps/quickbooks_online/utils.py
> +        value = value if value else 'Credit Card Misc'
if the vendor is empty, it will throw error

2023-08-10 11:18 UTC, ashwin1111 approved these changes

2023-08-16 07:30 UTC, merged